version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weakly'
      day: 'monday'
      time: '08:00'
      timezone: 'America/Santiago'

    open-pull-requests-limit: 5
    labels:
      - 'dependences'
      - 'seguridad'
    reviewers:
      - 'NiKoX23'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
    interval: 'weekly'